# compose.yml
services:
  antigravity:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USER_NAME: ${USERNAME:-developer}
        GROUP_NAME: ${USERNAME:-developer}
    image: antigravity-image:latest
    container_name: antigravity
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
    network_mode: host
    userns_mode: keep-id
    hostname: antigravity
    volumes:
      - ${HOME}/.gemini:/home/${USERNAME:-developer}/.gemini:Z
      - ${PWD}:/home/${USERNAME:-developer}/app:Z
      - antigravity-cli:/home/${USERNAME:-developer}/.local
    working_dir: /home/${USERNAME:-developer}/app

volumes:
  antigravity-cli:
